apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongo-secret
  namespace: three-tier
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: mongo-secret
    creationPolicy: Owner
  data:
    - secretKey: MONGO_INITDB_ROOT_USERNAME
      remoteRef:
        key: three-tier/mongo
        property: MONGO_INITDB_ROOT_USERNAME
    - secretKey: MONGO_INITDB_ROOT_PASSWORD
      remoteRef:
        key: three-tier/mongo
        property: MONGO_INITDB_ROOT_PASSWORD
    - secretKey: MONGO_CONN_STR
      remoteRef:
        key: three-tier/mongo
        property: MONGO_CONN_STR
